POST https://prod-20.australiasoutheast.logic.azure.com/workflows/b4406dbab3a34ecd9da53ff6e3b5fd5b/triggers/manual/paths/invoke/?api-version=2016-06-01&sp=/triggers/manual/run&sv=1.0
###
POST https://prod-20.australiasoutheast.logic.azure.com:443/workflows/b4406dbab3a34ecd9da53ff6e3b5fd5b/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=Ck6gL96cVpJL4NarRVnadC1zES7tPbWy6BjM4hSniLs
Content-Type: application/json

{ "test" : "1"}

###

POST https://apimtrainingbc.azure-api.net/msidemo/APIMTtraining_L1
Content-Type: application/json
Ocp-Apim-Subscription-Key: 


{ "test" : "1"}

###

POST https://apimtrainingfa.azurewebsites.net/api/HttpTrigger1?code=xnfWcLhOShzkBZXoYFna1p7UYDI4LPTlDgBmdyhih5oiwAfzOfroXQ==&name=bill

###


POST https://apimtrainingfa.azurewebsites.net/api/HttpTrigger1?name=bill

###
